# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-24 17:43
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20180623_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='课程详情'),
        ),
    ]
