# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180603_0010'),
        ('courses', '0002_auto_20180602_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
