# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-06 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180606_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='老师告诉你能学到什么'),
        ),
    ]
